apiVersion: v1

kind: Service

metadata:
  name: be-service
  labels:
    app: jump-the-queue

spec:
  selector:
    app: jump-the-queue
    tier: be-deployment 

  type: ClusterIP

  ports:
    - protocol: TCP
      port: 8081 
      targetPort: 8081
