:toc: macro
toc::[]

= devon4j Getting Started

== First steps
Here you get to know the basics of devon4j and the app _May-Thai-Star_.

- link:devon4j-overview[**devon4j overview**]
- link:an-devon4j-application[**an devon4j application**]

== Build your own application
In these chapters you will get to know the extension app of _May-Thai-Star_ _JumptheQueue_ and start to get it up and running.

- link:build-devon4j-application[**build your own devon4j application**]
- link:devon4j-components[**application components for devon4j**]

== Advanced knowledge
The structure of our devon4j project is shown here.

- link:devon4j-layers[**devon4j structure**]

== Expand your app
We extend our app and test the functionallity with a tool. We will also prove that the data used meets the practice requirements.

- link:devon4j-adding-custom-functionality[**adding custom functionality for devon4j**]
- link:devon4j-validations[**data validations for devon4j**]

== Test and deploy your app
These chapters give a glimpse into the possibilities of devon4j to test an app and finally create a .war file.

- link:devon4j-testing[**testing for devon4j**]
- link:devon4j-deployment[**deployment for devon4j**]
