:toc: macro
toc::[]
:idprefix:
:idseparator: -
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

= Home

== General Concept
This documentation serves as an introductory course to application development under devonfw. It is structured in an alternating fashion: First a general explanation of different components and features is provided -- using the complex _MyThaiStar_ application as an example, then the actual implementation of these aspects is demonstrated via code-examples -- which are part of the smaller _JumpTheQueue_ application.

Here's some general advice up front: 

* _Carefully_ read each chapter and use the provided instructions in combination with the screenshots to complete your application code.

* Work through the chapters in their _correct order_ by following the "*Next chapter:*" link at the bottom of each page.

* Don't get lost in all the _optional links_ provided within the text. They exist for the sake of completeness and you don't have to follow them unless explicitly stated.

* In Eclipse select the "Package Explorer" tab, press *Ctrl+F10* and under "Package Presentation" enable the option "Hierarchical" to gain a better overview over the project.

* If Eclipse shows any _warnings_, ignore them for the time being.

* If Eclipse detects _errors_ as a result of its static code analysis, read the displayed tooltips and consider applying the suggested solutions. If this doesn't resolve the issue or if you encounter runtime errors, do the following:

** _Backtrack_ your steps and make sure you haven't made any mistaktes previously. Be especially careful when using _CobigGen_, since generating wrong/unnecessary classes will most likely break the application.

** _Compare_ your own code with the finished application code in this repository to rule out any other potential mistakes. As a last resort you might copy/paste the provided files into your own project.

** If all of the above fails, ask your supervisor for help and provide them with a link to the respective section in this guide. This way we can correct possible errors and improve this introductory course for future trainees.

IMPORTANT: If you haven't already, please read the devonfw https://github.com/devonfw/getting-started/[getting started guide] for a basic overview over the framework, its components, the available resources and other related topics.

== Document Overview

=== devon4j
. link:devon4j-overview[]
. link:an-devon4j-application[]
. link:build-devon4j-application[]
. link:devon4j-components[]
. link:devon4j-layers[]
. link:devon4j-adding-custom-functionality[]
. link:devon4j-validations[]
. link:devon4j-testing[]
. link:devon4j-deployment[]

=== devon4ng
. link:devon4ng-introduction[]
. link:an-devon4ng-application[]
. link:angular-components[]
. link:angular-services[]
. link:build-devon4ng-application[]
. link:angular-deployment[]

////
=== OASP4Fn
. link:OASP4FnIntroduction[]
. link:BuildOASP4FnApplication[]
. link:OASP4FnTesting[]
. link:OASP4FnDeployment[]
////

'''
*First chapter:* link:jump-the-queue-design[]