name: CI Build
on: [push, pull_request]
jobs:
  build:
    if: ${{github.repository == 'devonfw/jump-the-queue'}}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: '11'
      # Spellcheck
      - uses: actions/checkout@v2
      - uses: igsekor/pyspelling-any@v0.0.2
      - name: Build project with Maven
        run: |
          cd java/jtqj
          mvn install

